### ISSUE TITLE
Add project to LFX Security ( create service desk request to trigger )

### ISSUE THREAD

**Issue by dchassin** [arras-energy/tsc#14]

**Comment by jmertic** [comment]
Working on this - will keep you posted.

**Comment by jmertic** [comment]
Hey @dchassin - I believe the need is to ensure the correct package files are in the repo, as Synk uses those to know the dependencies. I'm not sure of an external Synk dashboard integrating into LFX Security.

**Comment by dchassin** [comment]
@jmertic, TBH I have no idea what you're asking for. I was able to run Snyk on the code repositories no problem without making any changes to them. I'll email you the invite to Snyk in a minute.

**Comment by jmertic** [comment]
Hi @dchassin - it's online now: https://security.lfx.linuxfoundation.org/#/a092M00001L1HmTQAV/overview

Note that C/C++ scanning right now isn't working, but other languages with the correct manifest files should pick up fine. I recall us discussing this and there was some weirdness in how those manifest files were built, it would be to capture this to see how the LFX Security tool could best manage that.
